INSERT OR IGNORE INTO resources (resource_id, name, resource_group, rarity, description) VALUES
  (1, 'Carbon', 'Element', 'Common', 'Organic resource gathered from flora.'),
  (2, 'Condensed Carbon', 'Element', 'Common', 'Refined carbon resource.'),
  (3, 'Ferrite Dust', 'Element', 'Common', 'Basic mineral dust.'),
  (4, 'Pure Ferrite', 'Element', 'Common', 'Refined ferrite material.'),
  (5, 'Magnetised Ferrite', 'Element', 'Uncommon', 'Advanced ferrite resource.'),
  (6, 'Oxygen', 'Element', 'Common', 'Life support resource.'),
  (7, 'Sodium', 'Element', 'Common', 'Hazard protection resource.'),
  (8, 'Sodium Nitrate', 'Element', 'Uncommon', 'Refined sodium resource.'),
  (9, 'Di-hydrogen', 'Element', 'Common', 'Starship launch and fuel component.'),
  (10, 'Tritium', 'Element', 'Common', 'Pulse engine fuel resource.'),
  (11, 'Copper', 'Stellar Metal', 'Common', 'Yellow star system metal.'),
  (12, 'Cadmium', 'Stellar Metal', 'Uncommon', 'Red star system metal.'),
  (13, 'Emeril', 'Stellar Metal', 'Rare', 'Green star system metal.'),
  (14, 'Indium', 'Stellar Metal', 'Rare', 'Blue star system metal.'),
  (15, 'Activated Copper', 'Activated Stellar Metal', 'Uncommon', 'Storm-activated copper.'),
  (16, 'Activated Cadmium', 'Activated Stellar Metal', 'Rare', 'Storm-activated cadmium.'),
  (17, 'Activated Emeril', 'Activated Stellar Metal', 'Rare', 'Storm-activated emeril.'),
  (18, 'Activated Indium', 'Activated Stellar Metal', 'Rare', 'Storm-activated indium.'),
  (19, 'Cobalt', 'Cave Resource', 'Common', 'Underground mineral resource.'),
  (20, 'Ionised Cobalt', 'Cave Resource', 'Uncommon', 'Refined cobalt resource.'),
  (21, 'Salt', 'Ocean Resource', 'Common', 'Aquatic mineral resource.'),
  (22, 'Chlorine', 'Ocean Resource', 'Uncommon', 'Refined salt/ocean resource.'),
  (23, 'Ammonia', 'Biome Resource', 'Uncommon', 'Toxic biome resource.'),
  (24, 'Dioxite', 'Biome Resource', 'Uncommon', 'Frozen biome resource.'),
  (25, 'Phosphorus', 'Biome Resource', 'Uncommon', 'Scorched biome resource.'),
  (26, 'Paraffinium', 'Biome Resource', 'Uncommon', 'Lush biome resource.'),
  (27, 'Pyrite', 'Biome Resource', 'Uncommon', 'Desert biome resource.'),
  (28, 'Uranium', 'Biome Resource', 'Uncommon', 'Radioactive biome resource.'),
  (29, 'Nanites', 'Currency', 'Rare', 'Upgrade and technology currency.'),
  (30, 'Units', 'Currency', 'Common', 'Primary money currency.'),
  (31, 'Quicksilver', 'Currency', 'Rare', 'Anomaly mission currency.');
